import { HELP_EN } from './help-strings.ts';
// Local UI copy only; no API calls and no changes to user content or model output.
export const UI_EN: Record<string, string> = {
'，让回答有据可依。”':', to ground the answer.”', '未打开文档':'No document open', '释义 · 设置':'Plainly · Settings', '窗口预览':'Window preview', '启用功能':'Enabled features', '解释设置':'Explanation settings', 'PDF 阅读':'PDF reading', '浅色':'Light', '深色':'Dark', '简短':'Brief', '标准':'Standard', '详细':'Detailed', '输入或粘贴文字…':'Type or paste text…', '解释 ↗':'Explain ↗',
'释义 · 阅读，少一点不明白。':'Plainly · Read with understanding.', '释义':'Plainly', '你的阅读方式':'YOUR READING PREFERENCES', '阅读偏好':'Reading', '模型连接':'Models', '提示词':'Prompts', '文':'Aa', '翻译学习':'Languages', '页内搜索':'Page search', '用量统计':'Usage', '关于释义':'About', '轻一点，懂多一点。':'Less friction. More understanding.', '让理解，自然发生。':'Make understanding feel natural.', '设置保存在此设备':'Settings stay on this device', '已保存':'Saved', '保存修改':'Save changes', '保存中…':'Saving…', '有尚未保存的修改':'You have unsaved changes', '已保存到此设备':'Saved on this device',
'阅读，少一点不明白。':'Read with a little more clarity.', '一个词、一句黑话、一个陌生概念。':'A word, a slang phrase, an unfamiliar idea.', '选中它，让解释轻轻出现。':'Select it and let the meaning unfold.', '让解释如何出现':'How it appears', '触发方式':'Activation', '选中后，点一下':'Select, then click', '出现一个小按钮，需要时才解释。':'A small button appears. Click when you need it.', '推荐':'Recommended', '选中即解释':'Open on selection', '短暂停留后，自动展开解释。':'Open automatically after a short delay.', '仅手动触发':'Manual only', '通过右键菜单或快捷键解释。':'Use the context menu or keyboard shortcut.', '自动解释延迟':'Delay before opening', '随时用快捷键唤起':'Use the shortcut anytime', '修改 ↗':'Change ↗',
'划词按钮':'Selection button', '位置与图标':'Position & icon', '出现在选区的哪个角落':'Position around the selection', '左上角 ↖':'Top left ↖', '右上角 ↗':'Top right ↗', '左下角 ↙':'Bottom left ↙', '右下角 ↘':'Bottom right ↘', '距离选区 2 px，不遮住选中文字。':'2 px from your selection, without covering the text.', '屏幕边缘空间不足时自动避让。':'Automatically adjusts near screen edges.', '划词按钮位置预览':'Selection button position preview', '选中的词语':'Selected words', '按钮与图标大小':'Button & icon size', '20–56 px，图标等比例缩放，距文字仍为 2 px。':'20–56 px. Icons scale proportionally and stay 2 px from the text.', '可用图标':'Available icons', '上传图标':'Upload icon', '支持 PNG、JPG、WebP、GIF、SVG、ICO，最大 10 MB。上传后调整选框裁剪，确认后生成铺满按钮的方形静态图标。图片仅在本机处理。':'PNG, JPG, WebP, GIF, SVG or ICO, up to 10 MB. Adjust the crop to create a square icon that fills the button. Images are processed locally.',
'一个问号，几种用法':'One question mark, many ways to read', '可多选':'Select multiple', '选中的功能会集成在同一个划词窗口。只选一项时直接打开；Jev 页内检索保留独立入口。':'Selected features share one reading window. A single feature opens directly. Jev search has a separate entry.', '点击问号后默认打开':'Default feature when clicking the question mark', '解释':'Explain', '翻译':'Translate', '同语学习':'Learn', '英英词典':'Dictionary', '解释得刚刚好':'Just enough explanation', '结合附近上下文':'Use nearby context', '更准确地理解缩写、反讽和圈内用语。':'Better understand acronyms, irony, and insider language.', '默认解释模式':'Default explanation mode', '回答长度':'Answer length', '一句到几句 · 简短':'Brief · a few sentences', '刚好看懂 · 标准':'Standard · enough to understand', '展开讲讲 · 详细':'Detailed · explore further', '自定义字数':'Custom length', '目标输出字符数':'Target character count', '50–5000 字符，含标点与空格。仅用于解释及其追问，是模型的篇幅目标，不会强行截断正文。自定义系统提示词需保留 {{length}} 变量。':'50–5,000 characters including punctuation and spaces. Applies to explanations and follow-ups. This is a target, not a hard cutoff. Keep {{length}} in custom prompts.', '默认输出语言':'Default explanation language', '简体中文':'Simplified Chinese', '繁體中文':'Traditional Chinese', '系统语言（界面）':'Interface language', '界面语言':'Interface language', '仅改变界面文字，不改变模型输出语言。':'Changes interface text only, not the language of model responses.', '外观':'Appearance', '跟随系统':'System', '暖白':'Warm white', '石墨':'Graphite',
'PDF，直接读':'Read PDFs in place', '自动切换到释义 PDF 阅读器':'Automatically open PDFs in Plainly', '默认关闭，保留浏览器原生阅读器。选中文字后右键，即可在侧栏解释和翻译。':'Off by default, keeping the browser PDF viewer. Select text and right-click to explain or translate in the side panel.', '需要选区旁的问号、全文检索和原文高亮时，可从侧栏切换到释义阅读器。开启此项后，在线与已授权的本地 PDF 会自动切换。':'Switch from the side panel for the selection button, full-text search and highlights. Enable this to open online and authorized local PDFs automatically in Plainly.', '设置本地文件权限 ↗':'Local file permissions ↗', '文字与对话框':'Text & reading window', '恢复默认':'Reset to defaults', '拖动后点击空白处关闭':'Close on outside click after dragging', '默认关闭：拖动后自动锁定，图标同步显示为锁定。开启后拖动仍保持未锁定。标题栏的锁定按钮可临时切换当前提示框，× 或 Esc 始终可关闭。':'Off by default: dragging locks the window and updates the lock icon. Turn on to keep it unlocked after dragging. The title-bar lock toggles the current window; × or Esc always closes it.', '正文文字大小':'Text size', '正文文字大小数值':'Text size value', '对话框宽度':'Window width', '对话框宽度数值':'Window width value', '对话框最大高度':'Maximum window height', '对话框最大高度数值':'Maximum window height value', '让不熟悉的表达，变得清楚易懂。':'Make unfamiliar expressions feel clear.', '文字大小适用于解释、翻译、同语学习和词典正文。宽高用于网页和 PDF 的划词对话框；短回答按内容收紧，长回答在窗口内滚动。展开追问时宽度增加 90 px，空间不足时自动缩小。':'Text size applies to all reading features. Dimensions apply to selection windows on web pages and PDFs. Short answers fit their content; long answers scroll. Follow-ups add 90 px of width, subject to available space.', '安静的例外':'Quiet exceptions', '这些网站不自动显示划词按钮':'Hide the selection button on these sites', '每行一个域名，例如 mail.google.com':'One domain per line, e.g. mail.google.com', '仍可使用右键或快捷键。仅匹配填写的域名。':'Context menus and shortcuts still work. Only exact domains match.',
'一次刚刚好的解释':'A little clarity', '信息越来越多，':'More information,', '理解可以更轻松。':'less effort to understand.', '“我们先用':'“Let’s use', '让回答有据可依。”':'to ground the answer.”', '智能解释':'Smart explanation', '↳ 结合这句话的语境':'↳ With context from this sentence', '让 AI':'A way for AI to', '先查资料，再回答':'look up sources before answering', '的一种方法。':'.', '比如回答公司制度问题时，先从内部文档找到相关规定，再据此组织答案，减少凭空猜测。':'For example, find relevant company policies in internal documents before answering a question, reducing unsupported guesses.', '举个例子':'Give an example', '再讲简单点':'Make it simpler', '窗口尺寸示意':'Window size preview', '按最大高度演示；实际短回答会按内容收紧。预览空间不足时同比例缩小。':'Shows maximum height. Short answers fit their content. The preview scales down when space is limited.',
'连接你信任的模型。':'Connect a model you trust.', '使用自己的 API Key，直接连接模型服务。':'Use your own API key to connect directly.', '释义不设中转服务器。':'Plainly does not relay your requests.', '选择一个现成接口':'Choose a provider', '填入自己的 Key 即可测试':'Add your key to test', '点击添加独立配置，保留现有密钥和当前模型。模型可改为账户可用的其他名称。Jev 用于按意思找内容。新发布的 OpenAI Decisions API 暂未接入。':'Add a separate profile without replacing existing keys or the active model. You can enter any supported model ID. Jev powers semantic search. OpenAI Decisions API is not integrated.', '获取 API 与接入指南':'API setup guide', '需要时展开':'Expand when needed', '准备好三样东西：服务平台生成的 API Key、API 基础地址、账户可用的模型名称。点击上方预设可自动填入地址和模型。':'You need an API key, base URL and model ID. Provider presets fill in the URL and model for you.', '已有平台：去哪里获取 API Key':'Where to get API keys', '打开对应平台的官方指引，登录并在密钥管理中创建 Key，再回到本页填写。按平台要求开通 API 服务、额度和模型权限。':'Follow your provider’s official guide, sign in and create a key. Enable API access, credits and model permissions as required.', '开放平台 → API keys，创建密钥。':'Developer platform → API keys → Create key.', 'API 平台 → 项目 → API keys，创建项目密钥。':'API platform → Project → API keys → Create project key.', 'Claude Console → API keys，创建密钥。':'Claude Console → API keys → Create key.', 'Google AI Studio → API Keys，选择项目并创建。':'Google AI Studio → API Keys → Choose a project and create a key.', '通义千问 ↗':'Qwen ↗', '阿里云百炼 → API Key；密钥与接口地域需一致。':'Alibaba Cloud Model Studio → API Key. Match the key and endpoint region.', 'Kimi 开放平台 → API Keys；K3 需开通充值权限。':'Kimi developer platform → API Keys. K3 requires the appropriate account access.', '智谱开放平台 → API Keys；模型版本可自行修改。':'Zhipu developer platform → API Keys. You can change the model version.', '平台 → Keys；可用一个 Key 调用平台提供的不同模型。':'Platform → Keys. One key can access the platform’s available models.', '按官方快速开始获取 Key，再填入「页内搜索」。':'Get a key from the official quickstart, then enter it in Page search.', 'OpenRouter 默认的':'OpenRouter’s default', '会自动选模型，按实际模型计费；可在「模型名称」指定平台列出的完整 ID。这里接入的是各平台的 API 服务，请确认账户的 API 额度。':'selects a model automatically and bills for that model. Enter a full model ID to choose one explicitly. These are API services; check your API credits.',
'接入其他平台或第三方 API':'Other providers and third-party APIs', '点击「＋ 添加模型配置」，服务商选择「自定义 / 本地模型」，给配置起一个便于识别的名称。':'Click Add model profile, choose Custom / local model and name your profile.', '在第三方平台创建 API Key，填写该平台给你的完整「模型名称」。模型显示名与调用 ID 可能不同，请复制文档里的':'Create a key with the provider and enter its full model ID. Display names may differ; copy the documented', '值。':'value.', '展开「接口地址与协议」。将文档的':'Expand Endpoint & protocol. Copy the documented', '或':'or', '填入「API 基础地址」，保留它要求的版本路径。':'into API base URL, including the required version path.', '按平台提供的协议选择：标注 OpenAI 兼容或 Chat Completions 就选「OpenAI Chat Completions 兼容」；原生 Claude Messages 或 Gemini Generate Content 接口选择对应协议。协议由平台接口决定，与调用的模型品牌无关。':'Choose the protocol your provider implements: OpenAI Chat Completions compatible, Claude Messages or Gemini Generate Content. The endpoint determines the protocol, not the model brand.', '填入该平台的 Key，点击「测试连接」。成功后点击「设为当前使用」，再点顶部「保存修改」。测试会发送一条简短请求。':'Enter the provider’s key and test the connection. Then select Use this profile and Save changes. Testing sends a short request.', '填写示例 · OpenAI 兼容平台':'Example · OpenAI-compatible provider', '服务商':'Provider', '自定义 / 本地模型':'Custom / local model', 'API 基础地址':'API base URL', '接口协议':'Protocol', 'OpenAI Chat Completions 兼容':'OpenAI Chat Completions compatible', '模型名称':'Model ID', '复制平台文档中 model 的值':'Copy the model value from provider documentation', '填写这个第三方平台生成的密钥':'Use the key issued by this provider', 'example.com 仅为填写示例，请替换为实际地址。OpenAI 兼容接口也可填完整的 /chat/completions 地址；不要填平台官网、控制台网址或 /responses 地址。':'Replace example.com with the real endpoint. OpenAI-compatible services also accept a full /chat/completions URL. Do not use a website, dashboard or /responses URL.', '第三方平台的地址、密钥和模型 ID 要配套使用；选中文字和必要上下文会发送到你填写的平台。这里只支持三种已列出的协议；需要专用签名、额外必填请求头或仅提供 Responses 的接口暂不支持。':'Use the URL, key and model ID from the same provider. Selected text and necessary context go to that service. Only the three listed protocols are supported; custom signing, extra required headers and Responses-only APIs are not supported.',
'测试连接失败时，先检查这些':'Troubleshooting connection tests', '未获授权：':'Unauthorized:', '检查 Key 是否有效、是否属于这个平台和地域，以及模型权限。':'Check your key, provider, region and model permissions.', '找不到接口或模型：':'Endpoint or model not found:', '核对基础地址中的版本路径，以及模型完整 ID。':'Check the base URL version path and full model ID.', '参数不接受：':'Unsupported parameter:', '核对协议；若平台明确提示不支持':'Check the protocol. If the provider explicitly rejects', '，在「接口地址与协议」关闭「请求返回流式 token 用量」后重试。':'disable streaming token usage under Endpoint & protocol and try again.', '额度不足或请求频繁：':'Insufficient credits or rate limit:', '查看 API 余额和平台速率限制。':'Check API credits and rate limits.', '网络连接失败：':'Network connection failed:', '检查网络与平台状态，确认平台允许浏览器扩展访问。本地服务需运行中，并按服务文档允许扩展来源。':'Check network and provider status. The service must allow browser extension requests. Local services must be running and allow the extension origin.', '远程地址需使用 HTTPS。本地服务可用':'Remote endpoints require HTTPS. Local services can use', '等地址，模型名填写已安装的模型；本地接口允许留空 Key。若平台要求的接入方式超出上述范围，仅修改地址不能完成接入。':'or similar addresses with an installed model ID. Local keys may be left blank. Changing a URL alone cannot add an unsupported protocol.',
'＋ 添加模型配置':'＋ Add model profile', '连接设置':'Connection settings', '设为当前使用':'Use this profile', '✓ 当前使用':'✓ Active profile', '配置名称':'Profile name', '我的日常模型':'My everyday model', '仅保存在本机扩展中':'Stored locally in the extension', '粘贴你的 API Key':'Paste your API key', '显示':'Show', '隐藏':'Hide', '填写服务商提供的完整模型 ID':'Enter the full model ID from your provider', '以你账户可用的模型为准，也可以填写本地模型名称。':'Use a model available to your account, or a local model name.', '接口地址与协议':'Endpoint & protocol', '请求返回流式 token 用量（OpenAI 兼容接口）':'Request streaming token usage (OpenAI-compatible)', '默认开启。如自定义接口拒绝 stream_options 参数，可关闭此项；插件不会自动重发请求。':'On by default. Disable if your endpoint rejects stream_options. Requests are not retried automatically.', '地区端点或代理地址可在这里修改。本地模型可以不填密钥。':'Edit regional or proxy endpoints here. Local models may not need a key.', '测试连接':'Test connection', '删除配置':'Delete profile', '测试会发送一条简短请求，可能产生少量模型费用。':'Testing sends a short request and may incur a small charge.', '密钥不会发送给正在阅读的网页，也不会同步到其他设备。它保存在浏览器的本地扩展存储中，并非系统钥匙串。':'Keys are never sent to the page you are reading or synced to other devices. They are kept in local extension storage, not the system keychain.',
'每一种不懂，都有解法。':'A way to understand every question.', '不同内容，用不同的系统提示词。':'Different content, different system prompts.', '解释、翻译、同语学习和 Jev，都可以按你的习惯调整。':'Customize explanations, translation, learning and Jev to suit you.', '功能提示词':'Feature prompts', '恢复默认提示词':'Restore default prompt', '选择功能':'Choose a feature', '提示词内容':'Prompt content', '修改后点击右上角保存。免费翻译与词典不使用 LLM，因此没有提示词。':'Save changes at the top right. Free translation and dictionary services do not use LLM prompts.', '解释模式':'Explanation modes', '＋ 新建解释模式':'＋ New explanation mode', '模式设置':'Mode settings', '设为默认':'Set as default', '✓ 默认模式':'✓ Default mode', '模式名称':'Mode name', '简短说明':'Short description', '这个模式擅长解释什么？':'What does this mode explain best?', '系统提示词':'System prompt', '写清解释重点、语气和输出格式。这里的语言和风格要求优先于通用偏好。':'Describe the focus, tone and format. Language and style requirements here override general explanation preferences.', '复制为新模式':'Duplicate as new mode', '删除模式':'Delete mode', '划词卡片里可以临时切换模式；不会改动这里保存的默认模式。':'Switch modes temporarily in the reading window without changing the saved default.',
'读懂，也学会表达。':'Understand, and learn to express it.', '翻译成另一种语言，或用原语言讲得更明白。':'Translate into another language, or make the original clearer.', '在“阅读偏好”勾选功能，即可加入同一个问号按钮。':'Enable features in Reading to add them to the question mark button.', '双语翻译默认选项':'Translation defaults', 'LLM 使用“模型连接”中的当前配置。MyMemory 不需要密钥，适合短句；匿名免费额度为每日 5,000 字符，以服务商实时规则为准。':'LLM translation uses your active model profile. MyMemory needs no key and works best for short text. Anonymous use allows 5,000 characters per day, subject to provider rules.', '同语种学习':'Same-language learning', '默认自动跟随原文：中文用中文，日文用日文，英文用英文。也可手动指定学习输出语言；不受界面语言或双语翻译设置影响。':'Follows the original language by default: Chinese stays Chinese, Japanese stays Japanese, English stays English. You can specify a language manually. Interface and translation settings do not affect this choice.', '免费英英词典':'Free English dictionary', '单个英文词可直接查询 Free Dictionary API，无需 LLM Key。提供音标、词性、释义和可用的例句，并保留词条来源及许可说明。短语、整句和其他语言请使用同语学习。':'Look up a single English word using Free Dictionary API without an LLM key. Includes pronunciation, part of speech, definitions, available examples, sources and licensing. Use learning mode for phrases, sentences and other languages.', '自定义翻译与同语学习提示词 ↗':'Customize translation & learning prompts ↗', '每次请求，由你选择':'Your choice for every request', 'LLM 可结合附近上下文；免费翻译只发送选中文字，词典只发送单词。免费服务失败或额度不足时会提示，不会自动改用其他服务或产生 LLM 费用。':'LLMs may use nearby context. Free translation sends only the selection, and the dictionary sends only the word. Errors or quota limits never trigger another service or LLM charges automatically.', 'MyMemory 用量说明 ↗':'MyMemory usage limits ↗',
'跟随原文':'Follow original', '学习输出语言':'Learning output language', '自动跟随原文':'Auto · original language', '表达难度':'Difficulty', '学习难度':'Learning level', '自动跟随原文语言，改写、词汇、语法和例句均使用该语言。':'Automatically use the original language for rewrites, vocabulary, grammar and examples.', '已手动指定学习输出语言；改写和讲解都使用所选语言。':'Rewrites and explanations use your manually selected language.', '原文语言':'Source language', '目标语言':'Target language', '交换两种语言':'Swap languages', '翻译服务':'Translation service', '当前 LLM':'Active LLM', 'MyMemory · 免费':'MyMemory · Free', '学习注释':'Learning notes', '自动识别':'Auto-detect', 'A1 · 入门':'A1 · Beginner', 'A2 · 基础':'A2 · Elementary', 'B1 · 中级':'B1 · Intermediate', 'B2 · 中高级':'B2 · Upper intermediate', 'C1 · 高级':'C1 · Advanced', 'C2 · 精通':'C2 · Proficient', '开始翻译 ↗':'Translate ↗', '开始同语学习 ↗':'Start learning ↗', '查词 ↗':'Look up ↗', '同语学习 ↗':'Learn ↗', '翻译 ↗':'Translate ↗', '免费英英词典 · 只发送选中单词到 Free Dictionary API，不需要密钥。':'Free English dictionary · Sends only the selected word to Free Dictionary API. No key needed.', '仅将选中文字发送至 MyMemory。需指定原文语言，最多 500 字节，有每日免费额度。':'Sends only the selection to MyMemory. Choose a source language. Maximum 500 bytes, with a daily free quota.', '使用当前 LLM，可结合上下文。选择明确的原文语言后，可用 ⇄ 交换方向。':'Uses your active LLM with optional context. Choose a source language to swap direction with ⇄.',
'记得意思，也能找到。':'Remember the idea. Find the words.', '用一句话，找到本页里意思相近的内容。':'Describe an idea to find related passages on this page.', '由 Jev 理解，回到原文确认。':'Let Jev find it, then check the source.', '连接 Jev':'Connect Jev', '独立于解释模型':'Separate from your reading model', '仅保存在本机':'Stored on this device only', '粘贴 Typesafe / Jev 的 API Key':'Paste your Typesafe / Jev API key', '通过':'Visit', '获取密钥。':'to get a key.', '默认切分方式':'Default segmentation', '自动 · 段落优先，长段按句拆分':'Auto · paragraphs, with long passages split into sentences', '按句 · 精确到一句话':'Sentences · precise matches', '按段 · 保留更多上下文':'Paragraphs · more context', '搜索面板中也可以临时切换。特别长的段落或句子会继续拆分。':'Change this temporarily in the search panel. Very long sentences or paragraphs are split further.', '模型与接口地址':'Model & endpoint', '使用 Jev System One 协议，也支持兼容的代理地址。':'Uses Jev System One, including compatible proxy endpoints.', '测试会发送两条示例句子，可能产生少量接口费用。测试成功后记得保存。':'Testing sends two sample sentences and may incur a small charge. Save after testing.', '怎么找':'How to search', '自定义 Jev 排序提示词和相关性判断标准 ↗':'Customize Jev ranking & relevance prompts ↗', '打开普通网页，点击插件里的“在当前网页找一找”，或按 Alt + Shift + F。描述想找的内容，点击搜索；点击结果会滚动到原文并高亮。':'Open a web page and choose Search this page, or press Alt + Shift + F. Describe what you need and search. Click a result to scroll to and highlight the source.', '只有开始搜索时才会提取并发送已加载的正文。长页面会分批搜索，超过范围时会明确提示。结果是可能相关的几处线索，不保证找全。PDF 请通过插件中的“PDF 阅读器”打开，可搜索文档文字并跨页定位。扫描件没有文字层时不支持检索；图片、内嵌网页及尚未加载的网页内容暂不支持。':'Loaded text is extracted and sent only when you search. Long pages use batches with coverage notices. Results may not be exhaustive. Use Plainly’s PDF reader for document search and cross-page navigation. Scanned pages without text, images, embedded pages and unloaded content are not supported.', 'Jev 密钥仅保存在本机扩展存储中。近期搜索结果最多缓存 10 条、10 分钟；可在“关于释义”中清除。':'The Jev key stays in local extension storage. Up to 10 recent searches are cached for 10 minutes. Clear them in About.',
'每一次理解，用了多少。':'Know what each request uses.', '直接读取 API 返回的 token 用量。':'Uses token counts reported by the API.', '只统计本插件在此设备发出的请求，不额外调用查询接口。':'Counts this extension’s requests on this device, without extra API calls.', '已报告输入 token':'Reported input tokens', '已报告输出 token':'Reported output tokens', '已报告总 token':'Reported total tokens', 'API 请求次数':'API requests', '按模型累计':'Usage by model', '刷新':'Refresh', '模型 / 配置':'Model / profile', '输入':'Input', '输出':'Output', '总 token':'Total tokens', '请求':'Requests', '报告情况':'Reporting', '这些数字如何计算':'How these numbers work', '支持 OpenAI 兼容接口、Claude、Gemini 和 Jev 返回的官方用量字段。包含解释、翻译、同语学习、追问和连接测试。Jev 分批检索与重排按每次实际请求计数；本地缓存命中和免费翻译、词典不增加 LLM 用量。':'Reads official usage fields from OpenAI-compatible services, Claude, Gemini and Jev. Includes explanations, translation, learning, follow-ups and tests. Jev batches and reranking count per request. Cache hits and free services do not add LLM usage.', '缓存 token 已计入输入；思考 token 已计入输出，细分项不应再次相加。接口没有提供用量时显示“未提供”，不会估算为零。取消、超时或断流可能只收到部分用量，因此累计值可能低于服务商账单。':'Cached tokens are included in input and thinking tokens in output; do not add them again. Missing usage is marked unreported, not zero. Canceled or interrupted requests may report partial usage, so totals can be lower than provider billing.', '统计从更新后开始，仅保存在此设备，不记录原文、提示词或 API Key。它不包含你在其他应用中的用量，不代表账户余额或费用；账单以服务商后台为准。':'Usage is stored only on this device, without source text, prompts or keys. It excludes other apps and is not an account balance or bill. Refer to your provider for billing.',
'选中，读懂。':'Select. Understand.', '释义是一件小工具。':'Plainly is a small reading tool.', '让陌生的语言，不再打断好奇心。':'Keep unfamiliar language from interrupting curiosity.', '开始使用':'Get started', '在“模型连接”里填入 API Key 和模型名称，测试并保存。':'Enter your API key and model in Models, test, then save.', '打开普通网页，选中一个不理解的词语或句子。':'Open a web page and select an unfamiliar word or sentence.', '点击选区旁的问号，在原文旁边阅读解释。':'Click the question mark to read the explanation beside the source.', '几处刚刚好的细节':'A few thoughtful details', '按 Esc 或点击卡片外关闭。固定后可以继续滚动原文。卡片中的解释模式只对当前查询生效。展开后可以追问；切换新选区会开始新的解释。':'Press Esc or click outside to close. Lock the window to keep it while scrolling. Temporary mode changes affect only the current query. Expand for follow-ups; a new selection starts a new answer.', '数据与边界':'Data & limitations', '触发解释时，会向你配置的模型服务发送选中文字、必要的附近上下文、提示词，以及当前解释的追问记录。LLM 翻译和同语学习使用同一模型连接；免费翻译只向 MyMemory 发送选中文字，英英词典只向 Free Dictionary API 发送单词。页内搜索仅在主动搜索时向 Jev 发送页面正文片段与搜索描述。没有账户系统、分析追踪或后台页面扫描。':'Reading requests send selected text, necessary context, prompts and current follow-ups to your configured model. LLM translation and learning share that connection. Free translation sends only selected text to MyMemory; dictionary lookup sends only a word to Free Dictionary API. Page search sends passages and your query to Jev only when requested. No accounts, analytics or background page scanning.', '自动划词需要访问普通网页。浏览器内部页、Chrome 应用商店和内置 PDF 阅读器不支持此划词窗口；PDF 默认保留原生阅读器，选中文字后右键即可在侧栏解释和翻译；如需全文检索与原文高亮，可切换释义阅读器。本地链接需先开启文件访问权限。也可通过工具栏的“PDF 阅读器”手动打开；其他受限页面可以粘贴内容解释。输入框和可编辑区域默认不触发。':'Selection buttons work on ordinary web pages, not browser pages, the Chrome Web Store or the built-in PDF viewer. In native PDFs, select text and right-click to use the side panel. Switch to Plainly’s reader for search and highlights. Local URLs require file access. You can also open PDFs from the toolbar or paste text from restricted pages. Editable fields do not trigger the button.', '近期解释仅短暂缓存在扩展后台内存中，最多 40 条、有效期 10 分钟。AI 可能误解新梗、缩写或出处，重要信息请核实。':'Up to 40 recent answers are cached in extension memory for 10 minutes. AI may misunderstand slang, acronyms or sources; verify important information.', '清除近期缓存':'Clear recent cache', '释义 · PLAINLY':'PLAINLY', '为阅读留白。':'Room to read.',
'裁剪提示键图标':'Crop selection icon', '重置选框':'Reset crop', '拖动选框选择位置，拖动四角调整大小。框内就是最终图标；支持方向键微调。':'Move the crop box and drag its corners to resize. The area inside becomes your icon. Arrow keys make fine adjustments.', '完整原图':'Full source image', '裁剪选框，拖动或用方向键移动':'Crop box; drag or move with arrow keys', '调整左上角':'Resize top left', '调整右上角':'Resize top right', '调整左下角':'Resize bottom left', '调整右下角':'Resize bottom right', '裁剪后的图标预览':'Cropped icon preview', '图标预览':'Icon preview', '取消':'Cancel', '使用裁剪图标':'Use cropped icon',
'设置 ↗':'Settings ↗', '有什么不明白的？':'What would you like to understand?', '放进来，一起读懂。':'Paste it here. Let’s make it clear.', '阅读功能':'Reading features', '粘贴一个词、一句黑话，或一段陌生的表达…':'Paste a word, slang phrase, or unfamiliar passage…', '需要解释的内容':'Text to understand', '解释一下 ↗':'Explain ↗', '复制结果':'Copy result', '重试':'Retry', '⌕ 在当前网页找一找':'⌕ Search this page', '按意思搜索 ↗':'Search by meaning ↗', 'PDF 阅读器':'PDF reader', '打开文件 / 在线 PDF ↗':'Open file / online PDF ↗', '尚未连接模型':'No model connected', '先在设置中连接模型':'Connect a model in Settings', '留在原文旁，读懂。':'Understand beside the source.', '选中文字，右键选择“在侧栏解释 / 翻译”。':'Select text and right-click “Explain / translate in side panel”.', '全文检索与原文高亮 → 释义阅读器':'Search & source highlights → Plainly reader', '在释义中打开当前 PDF ↗':'Open this PDF in Plainly ↗',
'PDF 阅读器 · 释义':'PDF reader · Plainly', '释义设置':'Plainly settings', '留在原文里，慢慢读懂。':'Stay with the source. Read at your own pace.', '原生阅读器 ↗':'Native viewer ↗', '打开文件':'Open file', '在线链接':'Online URL', '按意思找 ↗':'Search by meaning ↗', '上一页':'Previous page', '第':'Page', '页码':'Page number', '页':'', '下一页':'Next page', '缩放':'Zoom', '适合宽度':'Fit width', 'PDF 在线地址':'PDF URL', '打开':'Open', '收起':'Collapse', '重试打开':'Try opening again', '开启本地文件访问 ↗':'Enable local file access ↗', '让 PDF，也能轻松读懂。':'Make PDFs easier to understand.', '打开一份文档，选中文字，点击熟悉的小问号。':'Open a document, select text and click the question mark.', '解释、翻译和同语学习，都留在原文旁。':'Explain, translate and learn alongside the original.', '选择 PDF 文件 ↗':'Choose a PDF file ↗', '本地解析，文件不会上传。使用模型功能时才发送选中文字；':'Parsed locally; the file is never uploaded. Selected text is sent only when using model features;', '主动搜索时向 Jev 发送文档文字片段。单份文件最大 50 MB。':'search sends document passages to Jev. Maximum file size: 50 MB.', '支持带文字层的 PDF。扫描件暂无 OCR，暂不支持直接划词。':'Supports PDFs with a text layer. Scanned documents require OCR, which is not available yet.', '这份 PDF 需要密码':'This PDF needs a password', '文档密码':'Document password', '密码不正确，请重试。':'Incorrect password. Try again.', '密码仅用于在本机打开文件。':'The password is used only to open the file locally.'
};
Object.assign(UI_EN, {
'请至少保留一项功能。':'Keep at least one feature enabled.', '问号':'Question mark', '内置头像':'Built-in avatar', '选择问号':'Choose question mark', '选择内置头像':'Choose built-in avatar', '删除内置头像':'Delete built-in avatar', '已选择图标，保存修改后生效。':'Icon selected. Save changes to apply.', '图标已删除，已切回问号；保存修改后生效。':'Icon deleted; switched to the question mark. Save to apply.', '图标已删除，保存修改后生效。':'Icon deleted. Save changes to apply.', '最多保存 20 套配置。':'You can save up to 20 profiles.', '语义检索 · jev-latest':'Semantic search · jev-latest', '待接入 · 暂不可用':'Not yet available', '这个新接口暂未接入，当前可选 Jev 进行语义检索。':'This API is not integrated yet. Use Jev for semantic search.', '等待配置模型':'Model not configured', '使用中':'Active', '自定义解释方式':'Custom explanation', '默认':'Default', '本地文件访问已开启':'Local file access enabled', '本地 PDF 需开启“允许访问文件网址”':'Local PDFs require “Allow access to file URLs”', '可以直接使用自然语言描述你的要求，无需填写变量。':'Describe your requirements in plain language; no variables needed.', '正在测试搜索连接…':'Testing search connection…', '正在处理图标…':'Processing icon…', '已取消裁剪，保留原图标。':'Crop canceled. Original icon kept.', '最多保存 20 张上传图标，请先删除不需要的图标。':'You can save up to 20 uploaded icons. Delete an unused icon first.', '图标已准备好，点击右上角“保存修改”后生效。':'Icon ready. Click Save changes at the top right to apply.', '新模型配置':'New model profile', '正在连接…':'Connecting…', '最多保存 30 个模式。':'You can save up to 30 modes.', '我的解释模式':'My explanation mode', '恢复这个模式的原始提示词？':'Restore this mode’s original prompt?', '请填写范围内的有效数值。':'Enter a valid value within the allowed range.', '已清除':'Cleared',
'打开释义':'Open Plainly', '关闭释义':'Close Plainly', '关闭 · Esc':'Close · Esc', '锁定提示框':'Lock reading window', '已结合上下文':'Using nearby context', '正在处理选中文字':'Processing selected text', '模型设置 ↗':'Model settings ↗', '追问':'Follow-up', '还有哪里不明白？':'What else would you like to understand?', '发送追问':'Send follow-up', '打开设置':'Open settings', '选项已更改，点击上方按钮开始。':'Options changed. Click the button above to start.', '停止':'Stop', '已停止':'Stopped', '已停止，可重新尝试。':'Stopped. You can try again.', '收起 ↙':'Collapse ↙', '展开 ↗':'Expand ↗', '已复制':'Copied', '请选择正文复制':'Select the answer to copy', '拖动标题栏移动提示框':'Drag the title bar to move the window', '按住六点手柄拖动，或用方向键微调':'Drag the handle or use arrow keys to move', '按住拖动 · 方向键微调':'Drag to move · Arrow keys to adjust', '移动提示框，支持拖动或方向键':'Move window by dragging or with arrow keys', '已锁定 · 点击空白保留，点击此处解锁':'Locked · Stays open on outside click. Click to unlock.', '未锁定 · 点击空白关闭，点击此处锁定':'Unlocked · Closes on outside click. Click to lock.', '已结合上下文 · 查看发送内容':'Context included · View sent text', '仅解释选中文字 · 查看发送内容':'Selected text only · View sent text', '正在补充解释…':'Adding detail…', '正在理解这段内容…':'Understanding this passage…', '正在查询免费词典，可随时停止…':'Looking up the free dictionary. You can stop anytime…', '正在翻译…':'Translating…', '正在整理学习说明…':'Preparing learning notes…', '仅发送选中文字 · 查看':'Only selected text is sent · View', '仅使用选中文字 · 查看':'Selected text only · View', '已达到输出上限，请缩短选中文字后重试。':'Output limit reached. Select less text and try again.', '已达到输出上限。可以缩短选中文字后重试。':'Output limit reached. Select less text and try again.', '来自近期解释':'From recent explanations', '来自近期结果':'From recent results', '词条由 Free Dictionary API 提供':'Entry provided by Free Dictionary API', '译文来自 MyMemory；可切换 LLM 比较':'Translation by MyMemory; switch to LLM to compare', '译文来自 MyMemory':'Translation by MyMemory', '同语种学习 · 由当前 LLM 生成':'Learning notes · Generated by your active LLM', '由 LLM 翻译，请结合语境判断':'LLM translation; check against the context', '由 AI 解释，请结合语境判断':'AI explanation; check against the context', '由 AI 解释或翻译，请结合语境判断':'AI explanation or translation; check against the context', '请选中正文后复制。':'Select the answer text to copy.',
'释义 · 页内语义搜索':'Plainly · Semantic page search', '在这一页，找一找。':'Find it on this page.', '关闭搜索':'Close search', '搜索描述':'Search description', '描述你记得的意思，不必记住原词…':'Describe the idea, even if you forget the wording…', '切分方式':'Segmentation', '自动 · 段落优先':'Auto · paragraphs first', '按句查找':'By sentence', '按段查找':'By paragraph', '用自己的话，描述要找的内容。':'Describe what you need in your own words.', '点击搜索后，将本页已加载的正文片段发送至你配置的 Jev 服务。寻找最相关的几处，不保证找全。':'Searching sends loaded passages to your configured Jev service. Results show likely matches and may not be exhaustive.', '连接 Jev，开始搜索 ↗':'Connect Jev to search ↗', '上一个结果':'Previous result', '下一个结果':'Next result', '↑ 上一个':'↑ Previous', '↓ 下一个':'↓ Next', 'PLAINLY · 语义搜索':'PLAINLY · SEMANTIC SEARCH', '打开 ·':'Open ·', '关闭':'Close', '收起搜索':'Collapse search', '切分方式已更改，请重新搜索。':'Segmentation changed. Search again to update results.', '描述已更改，按 Enter 开始新搜索。':'Description changed. Press Enter to search again.', '设置已更新，可以重新搜索。':'Settings updated. You can search again.', '先在设置的“页内搜索”中连接 Jev。':'Connect Jev in Page search settings first.', '插件已更新，请刷新网页后重试。':'Extension updated. Refresh the page and try again.', '停止搜索':'Stop search', '找一找 ↗':'Search ↗', '展开搜索':'Expand search', '已停止搜索。':'Search stopped.', '正在提取本页正文…':'Reading the page text…', '当前页面没有可搜索的正文。PDF 请使用插件内的 PDF 阅读器打开。':'No searchable text on this page. For PDFs, use Plainly’s PDF reader.', '已搜索范围内未找到明确结果。试试换一种描述。':'No clear matches in the searched text. Try a different description.', '可能相关，但还不确定。点击原文查看。':'Possibly related, but uncertain. Open the source to check.', '找到相关线索。以下片段可能相关，点击定位。':'Possible matches found. Click a passage to locate it.', '原文片段':'Source passage',
'请在独立标签页打开 PDF。':'Open the PDF in its own tab.', 'PDF 阅读器仅允许在独立标签页运行。':'The PDF reader requires its own tab.', '在这份 PDF，找一找。':'Find it in this PDF.', '点击搜索后，将文档文字片段发送至你配置的 Jev 服务。最多扫描前 200 页，超出搜索范围会提示；不上传 PDF 文件。':'Searching sends document passages to your configured Jev service. Up to the first 200 pages are scanned, with coverage notices. The PDF file is not uploaded.', '已扫描页面没有可搜索的文字层。扫描件暂不支持 OCR；可以尝试其他带文字层的 PDF。':'No searchable text layer found. OCR is not available; try a PDF with a text layer.', '文档已更换，请重新搜索。':'Document changed. Search again.', '页面已变化，请再次点击结果。':'Page changed. Click the result again.', '无法定位这个片段，请重新搜索。':'Cannot locate this passage. Search again.', '该片段没有可定位的文字层。':'This passage has no locatable text layer.', '请先打开 PDF。':'Open a PDF first.', '选中文字，点击问号。按意思搜索可以跨页定位。':'Select text and click the question mark. Semantic search can find passages across pages.', '这一页没有可选文字，可能是扫描件。暂不支持 OCR；其他页仍可尝试。':'This page has no selectable text and may be scanned. OCR is unavailable; try another page.', '这一页无法显示，请尝试其他页或重新打开 PDF。':'This page could not be displayed. Try another page or reopen the PDF.', '文件超过 50 MB，请使用较小的 PDF。':'File exceeds 50 MB. Use a smaller PDF.', '在线文件没有内容。':'The online file is empty.', '无法读取本地 PDF，请检查文件是否存在，以及文件访问权限。':'Cannot read the local PDF. Check the file and access permissions.', '文件超过 50 MB，无法在释义中打开。':'File exceeds Plainly’s 50 MB limit.', '文件为空或超过 50 MB。':'File is empty or exceeds 50 MB.', '正在打开 PDF…':'Opening PDF…', '本地 PDF':'Local PDF', '在线 PDF':'Online PDF', '首次读取本地 PDF：请开启扩展的“允许访问文件网址”，之后直接打开文件即可。':'Enable “Allow access to file URLs” for this extension to open local PDFs directly.', '已取消打开加密 PDF。':'Opening encrypted PDF canceled.', '文件不是有效的 PDF，或链接返回了网页。请下载 PDF 后重新打开。':'The file is not a valid PDF, or the URL returned a web page. Download the PDF and reopen it.', '下载超时，请重试或下载后打开。':'Download timed out. Retry or download the file first.', '无法读取这份 PDF。该网站可能限制插件访问，可以切回原生阅读器。':'Cannot read this PDF. The site may restrict extension access. Try the native viewer.', '无法打开这份 PDF。':'Cannot open this PDF.',
'还没有记录。使用模型功能或测试连接后，会自动开始统计。':'No usage yet. Counts begin when you use a model or test a connection.', '缓存读取':'Cache read', '缓存写入':'Cache write', '思考':'Thinking', '请选择 PNG、JPG、WebP、GIF、SVG 或 ICO 图片。':'Choose a PNG, JPG, WebP, GIF, SVG or ICO image.', '图片不能超过 10 MB，请选择更小的图片。':'Choose an image under 10 MB.', '无法读取这张图片，请换一张有效图片。':'Cannot read this image. Try another file.', '图片没有有效尺寸，请换一张图片。':'The image has invalid dimensions. Try another file.', '图片尺寸过大，请缩小到 4000 万像素以内。':'Reduce the image to fewer than 40 million pixels.', '当前浏览器无法处理图片。':'This browser cannot process the image.', '无法保存裁剪结果，请换一张图片。':'Cannot save the crop. Try another image.', '插件连接已更新，请刷新页面后重试。':'Extension connection updated. Refresh the page and try again.', '连接已中断，请重试。若插件刚更新，请刷新网页。':'Connection interrupted. Retry, or refresh the page if the extension was updated.', '还没有填写模型名称，请到设置中完成配置。':'Add a model ID in Settings.', '还没有填写 API Key，请到设置中完成配置。':'Add an API key in Settings.', '模型服务返回错误，请检查服务状态或重试。':'Model service error. Check service status or try again.', '模型未返回解释，可能触发了服务商的内容限制。':'No answer returned. The provider may have applied a content restriction.', '连接未获授权：请检查 API Key、模型权限和接口地址。':'Unauthorized. Check the API key, model permissions and endpoint.', '请求过于频繁或额度不足，请稍后再试或检查账户余额。':'Rate limit or insufficient credits. Retry later or check your account.', '没有找到接口或模型，请核对 API 地址和模型名称。':'Endpoint or model not found. Check the API URL and model ID.', '接口不接受当前请求，请检查模型名称、协议及模型是否支持文本对话。':'Request rejected. Check the model ID, protocol and text support.', '接口返回了空响应。':'The API returned an empty response.', '模型服务返回错误，请检查配置。':'Model service error. Check your configuration.', '接口返回了无法读取的流式数据，请检查服务兼容性。':'Unreadable streaming response. Check service compatibility.', '连接中断，解释尚未完成，请重试。':'Connection interrupted before completion. Try again.', '模型没有返回正文，请尝试其他模型或稍后重试。':'No answer text returned. Try another model or retry later.',
'词典暂未收录这个词，请试试词语原形，或切换“同语学习”使用 LLM。':'Word not found. Try its base form or switch to learning with an LLM.', '免费服务当前限流或额度已用完，请稍后重试，或手动切换 LLM。':'Free service rate limit or quota reached. Retry later or manually switch to LLM.', '免费语言服务返回了无法识别的内容，请重试。':'The free service returned an unreadable response. Try again.', 'MyMemory 需要明确的原文语言，请先选择原文语言。':'Choose a source language before using MyMemory.', '两种语言相同；如需原语言改写，请切换“同语学习”。':'Both languages are the same. Use learning mode to rewrite in the original language.', 'MyMemory 单次最多 500 字节（中文约 160 字），请缩短选区，或手动切换 LLM。':'MyMemory allows 500 bytes per request. Select less text or manually switch to LLM.', 'MyMemory 免费额度已用完，请稍后重试，或手动切换 LLM。':'MyMemory free quota reached. Retry later or manually switch to LLM.', 'MyMemory 未能返回译文，请核对语言方向或稍后重试。':'MyMemory returned no translation. Check the languages or retry later.', '免费英英词典支持单个英文单词；句子、短语或其他语言请使用“同语学习”。':'The free dictionary supports single English words. Use learning for phrases, sentences and other languages.', '词典未返回有效词条，请试试词语原形。':'No valid dictionary entry. Try the word’s base form.', '词典没有提供释义，请换一个词重试。':'No definition available. Try another word.',
'网络黑话 / 梗':'Slang & memes', '专业术语':'Technical terms', '缩写解析':'Acronyms', '句子讲解':'Sentences', '读懂语境，选择恰当的解释方式。':'Choose the right explanation for the context.', '看懂圈内含义、潜台词和语气。':'Understand insider meanings, subtext and tone.', '保留准确性，把专业概念讲简单。':'Make technical ideas clear without losing accuracy.', '找出全称，结合上下文消除歧义。':'Expand acronyms and resolve ambiguity with context.', '理清复杂表达，说明话外之意。':'Clarify complex expressions and implied meanings.', '解释 · 通用系统提示词':'Explain · General system prompt', '双语翻译 · 系统提示词':'Translation · System prompt', '同语学习 · 系统提示词':'Learning · System prompt', 'Jev · 片段排序':'Jev · Passage ranking', 'Jev · 是否存在相关内容':'Jev · Relevance check', 'Jev · 相关的判定标准':'Jev · Relevant criteria', 'Jev · 不相关的判定标准':'Jev · Irrelevant criteria', '快捷追问 · 举个例子':'Follow-up · Example', '快捷追问 · 再讲简单点':'Follow-up · Simpler', '适用于所有解释模式。{{modePrompt}} 会填入下方所选模式的提示词；移除后将不再使用模式提示词。':'Used by all explanation modes. {{modePrompt}} inserts the selected mode’s prompt; removing it omits that prompt.', '仅对 LLM 翻译生效。变量分别对应原语言、目标语言和学习注释选项。':'Applies to LLM translation only. Variables represent source language, target language and learning notes.', '难度变量对应 A1–C2；学习语言默认跟随原文，可在翻译学习中手动指定。语言设置优先于提示词里冲突的语言要求。':'Difficulty uses A1–C2. Learning follows the original language unless manually specified in Languages. That setting overrides conflicting language instructions in the prompt.', '说明如何理解搜索意图、比较片段。搜索描述和正文会单独传入，适用于网页和 PDF。':'Describe how to interpret intent and compare passages. Queries and passages are provided separately for web pages and PDFs.', '说明如何判断当前搜索范围内是否有答案。':'Describe how to determine whether the searched text contains an answer.', '满足什么条件应认为有相关内容。':'Define what counts as relevant content.', '满足什么条件应认为没有相关内容。Jev 的结构化返回格式由插件管理。':'Define what counts as irrelevant content. The extension manages Jev’s structured response format.', '点击“举个例子”时发送的追问内容，最多 1000 字符。':'Follow-up sent by Give an example, up to 1,000 characters.', '点击“再讲简单点”时发送的追问内容，最多 1000 字符。':'Follow-up sent by Make it simpler, up to 1,000 characters.', '在侧栏解释 / 翻译':'Explain / translate in side panel', '通义千问':'Qwen'
});

Object.assign(UI_EN, {
  '跟随系统语言':'Follow interface language',
  '选择“跟随系统语言”的输出会同步切换；指定语言和跟随原文的选项保持不变。':'Outputs set to follow the interface language change with it. Fixed languages and follow-original choices stay unchanged.',
  '解释输出':'Explanation output', '翻译目标':'Translation target',
  '让解释和翻译跟随系统':'Set explanation & translation to follow interface',
  '各项语言都可在对应配置中修改，保存后生效。已有固定语言不会自动改写；自定义提示词若指定了语言，请同步调整。':'Each language choice is editable in its settings and applies after saving. Fixed languages are preserved. Check custom prompts for explicit language instructions.',
  '学习输出跟随系统语言；改写和讲解都使用当前系统语言。':'Learning output follows the interface language for both rewrites and explanations.',
  'Free Dictionary API · 英英词典':'Free Dictionary API · English dictionary', 'MyMemory · 免费翻译':'MyMemory · Free translation'
});

// Guide headings can share labels with compact controls; keep the existing UI wording.
for (const [source, translation] of Object.entries(HELP_EN)) UI_EN[source] ??= translation;

Object.assign(UI_EN, {
  '停止生成': 'Stop generating',
  '选中文字：': 'Selected text:', '附近上下文：': 'Nearby context:',
  '此操作只能在插件设置页执行。': 'This action is only available in extension settings.',
  '请在 PDF 阅读器中使用这个操作。': 'Use this action in the PDF reader.',
  '未知操作。': 'Unknown action.',
  '请求超时或已取消，请重试。': 'Request timed out or was canceled. Try again.',
  '无法连接模型服务，请检查网络、API 地址及服务是否允许浏览器访问。': 'Cannot connect to the model service. Check your network, API URL and whether the service allows browser access.',
  '暂时无法解释，请重试。': 'Unable to explain right now. Try again.',
  '本次搜索超时，请重试。': 'Search timed out. Try again.',
  '等待模型响应超时，请重试或更换模型。': 'The model took too long to respond. Retry or choose another model.',
  '免费翻译和词典不支持追问，请切换 LLM。': 'Free translation and dictionary lookup do not support follow-ups. Switch to an LLM.',
  '请在普通网页中打开页内搜索。PDF 请先使用插件中的 PDF 阅读器打开。': 'Open page search on a regular web page. For PDFs, use Plainly’s PDF reader.',
  '这个页面不允许插件运行，请换一个普通网页。': 'Extensions cannot run on this page. Try a regular web page.',
  '待设置模型': 'Model setup needed', '未配置模型': 'Model not configured', '未命名': 'Untitled',
  '请填写有效的 API 地址。': 'Enter a valid API URL.',
  'API 地址不能包含密码、查询参数或锚点。': 'API URLs cannot contain passwords, query parameters or fragments.',
  '远程接口需要 HTTPS；本地模型可使用 localhost 的 HTTP 地址。': 'Remote endpoints require HTTPS. Local models may use HTTP on localhost.',
  '请为问号按钮至少保留一项功能。': 'Keep at least one feature enabled for the selection button.',
  '图标无效，请重新上传图片。': 'Invalid icon. Upload the image again.',
  '图标库无效，最多保存 20 张上传图标。': 'Invalid icon library. You can save up to 20 uploaded icons.',
  '设置格式无效。': 'Invalid settings format.',
  '请保留 1–20 套模型配置。': 'Keep between 1 and 20 model profiles.',
  '不支持的接口协议。': 'Unsupported API protocol.',
  '请保留 1–30 个解释模式。': 'Keep between 1 and 30 explanation modes.',
  '模式名称和系统提示词不能为空。': 'Mode name and system prompt cannot be empty.',
  '配置标识重复。': 'Duplicate profile identifiers.',
  '请先选择需要解释的文字。': 'Select some text to explain first.',
  '一次最多解释 4000 个字符，请缩小选区。': 'Select no more than 4,000 characters at a time.',
  '请先在设置的“页内搜索”中填写 Jev API Key。': 'Add your Jev API key in Page search settings first.',
  'Jev 授权失败，请检查 API Key 与账户权限。': 'Jev authorization failed. Check your API key and account permissions.',
  'Jev 当前繁忙或请求额度不足，请稍后重试。': 'Jev is busy or your request quota is exhausted. Try again later.',
  'Jev 接口或模型配置不匹配，请核对地址和模型名称。': 'Jev endpoint or model mismatch. Check the URL and model name.',
  '正在按含义查找…': 'Searching by meaning…',
  '正在分段搜索长网页…': 'Searching page sections…',
  '正在整理相关片段…': 'Ranking related passages…',
  '本次搜索未完成，请重试。': 'Search did not finish. Try again.',
  '请填写 PDF 文件的完整在线地址。': 'Enter the full URL of the PDF file.',
  '在线 PDF 仅支持 HTTP / HTTPS 链接；本地文件请用“打开文件”。': 'Online PDFs require an HTTP or HTTPS URL. For local files, use Open file.',
  '请描述你想在本页找到的内容。': 'Describe what you want to find on this page.',
  '搜索描述最多 400 个字符。': 'Search descriptions can contain up to 400 characters.',
  '当前页面没有可搜索的正文。': 'There is no searchable text on this page.',
  '页面片段过多，请缩小搜索范围。': 'Too many passages. Narrow the search scope.',
  '页面片段格式无效，请重新提取。': 'Invalid passage format. Extract the page text again.',
  '本次页面内容超出搜索上限，请缩小范围。': 'Page content exceeds the search limit. Narrow the scope.',
  'Jev 响应格式不符合预期，请检查接口与模型配置。': 'Unexpected Jev response format. Check the endpoint and model settings.',
  'Jev 没有返回完整的片段排序，请重试。': 'Jev returned an incomplete passage ranking. Try again.',
  'Jev 返回的片段排序无效，请重试。': 'Jev returned an invalid passage ranking. Try again.',
  '页面内容已变化，请重新搜索。': 'Page content has changed. Search again.',
  '该片段当前不可见，请重新搜索。': 'This passage is no longer visible. Search again.'
});

Object.assign(UI_EN, {
  '内置提示词语言': 'Built-in prompt language',
  '当前内置提示词版本：English': 'Current built-in prompt version: English',
  '当前内置提示词版本：简体中文': 'Current built-in prompt version: Simplified Chinese',
  '内置提示词 · English': 'Built-in prompt · English',
  '内置提示词 · 简体中文': 'Built-in prompt · Simplified Chinese',
  '自定义提示词 · 保留原文': 'Custom prompt · Kept as written',
  '默认跟随界面，切换内置提示词、解释模式、请求说明及快捷追问的中英文版本。下方显示实际模板，保存后用于新请求；输出语言仍由各功能的语言配置决定。': 'Follows the interface by default, switching built-in prompts, explanation modes, request instructions and quick follow-ups between Chinese and English. The actual templates appear below and apply to new requests after saving. Each feature’s language setting still controls the output language.',
  '修改过的提示词保留原文，不自动翻译。可点击“恢复默认提示词”重新使用随语言切换的内置版本。': 'Edited prompts stay as written and are not automatically translated. Use Restore default prompt to return to the built-in version that follows the prompt language.'
});

Object.assign(UI_EN, {
  '写清解释重点、语气和输出格式。输出语言始终以语言配置为准，优先于模式及自定义提示词中的冲突要求。': 'Describe the focus, tone and output format. The language setting controls the output language and overrides conflicting instructions in modes and custom prompts.',
  '解释、翻译、同语学习和追问都追加独立的输出语言约束，语言配置优先于模式和自定义提示词中的冲突要求。正文、小标题、释义、语法与例句使用同一输出语言；必要原词和专名可以保留。自动同语学习仅按选中文字判断语言，上下文只用于消歧。自定义提示词保留原文。': 'Explanations, translations, learning and follow-ups append an independent output-language rule. Language settings override conflicting mode and custom-prompt instructions. Prose, headings, definitions, grammar and examples use the output language; necessary original terms and names may remain unchanged. Automatic learning identifies the language of the selection itself, using context only for meaning. Custom prompts stay as written.',
  '原文、已生成的回答、自定义提示词及自定义名称保持原样。未修改的内置模式名称和简介随界面切换。英英词典保留英文释义，搜索摘录保留原文语言。所有生成模式都按本次语言配置追加独立约束。': 'Source text, existing answers, custom prompts and custom names stay unchanged. Unedited built-in mode names and descriptions follow the interface. Dictionary definitions remain in English and search excerpts retain their original language. Every generation mode appends its current language requirement.',
  '先单独识别选中文字的语言，再锁定该语言讲解。首次识别会增加一次短 LLM 请求，计入用量；手动选择语言可跳过。': 'Identify the selection’s language first, then lock the lesson to that language. Initial detection adds a short LLM request counted in usage. Selecting a language manually skips detection.',
  '无法确定原文语言，请在同语学习中手动选择输出语言后重试。': 'Could not identify the source language. Select a learning output language manually and try again.',
  '各项语言都可在对应配置中修改，保存后生效。已有固定语言不会自动改写；语言配置优先于自定义提示词中的冲突要求。': 'Change each language in its settings and save to apply. Existing fixed languages stay unchanged; language settings override conflicting custom-prompt instructions.',
  '自动同语学习会先向当前模型发送选中文字，单独识别原文语言，再将识别结果写入输出语言约束。识别不发送附近上下文；短期内相同文字可复用结果。识别请求会计入用量，可能增加等待时间；手动指定语言可跳过。无法识别时会提示手动选择，不会静默改用界面语言。短词及多语言共有词可能存在歧义，可手动指定。': 'Automatic learning first sends the selection alone to the current model to identify its language, then adds that language to the output constraint. Detection excludes nearby context, and recent results for the same text may be reused. Detection counts toward usage and may add latency; manual language selection skips it. If identification fails, you are asked to select a language instead of silently falling back to the interface language. Short words and words shared across languages may be ambiguous; choose manually when needed.',
});

Object.assign(UI_EN, {'隐私与数据使用说明 ↗': 'Privacy & data use ↗'});

Object.assign(UI_EN, {'使用模型功能时，选中文字、开启的附近上下文及追问会直接发送至你配置的服务商；自动解释需主动开启。': 'Model features send selected text, enabled nearby context and follow-ups directly to your configured provider. Automatic explanations are opt-in.'});

Object.assign(UI_EN, {'点击添加独立配置，保留现有密钥和当前模型。模型可改为账户可用的其他名称。Jev 用于按意思找内容。OpenAI 预设使用 Chat Completions 协议。': 'Add a separate profile without changing existing keys or the active model. Choose any model available to your account. Jev searches by meaning. The OpenAI preset uses Chat Completions.'});
